warehouse:
  sensors:
    temperature:
      port: 3344
      threshold: 35
      simulation:
        min-value: 30
        max-value: 39
        interval-ms: 5000
    humidity:
      port: 3355
      threshold: 50
      simulation:
        min-value: 40
        max-value: 54
        interval-ms: 7000
    corbon:
      port: 3356
      threshold: 51
      simulation:
        min-value: 41
        max-value: 55
        interval-ms: 2000